package storage

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

type MinioClient struct {
	client        *minio.Client // internal endpoint — used for all data operations
	presignClient *minio.Client // public endpoint — used only for presigned URL generation
	bucket        string
}

// NewMinioClient connects to MinIO and ensures the target bucket exists.
// publicURL is the browser-reachable base URL (e.g. "http://localhost:9000").
// Presigned URLs are generated by a separate client configured with that public
// host so the HMAC signature matches what browsers actually request.
func NewMinioClient(endpoint, accessKey, secretKey, bucket string, useSSL bool, publicURL string) (*MinioClient, error) {
	client, err := minio.New(endpoint, &minio.Options{
		Creds:        credentials.NewStaticV4(accessKey, secretKey, ""),
		Secure:       useSSL,
		Region:       "us-east-1",
		BucketLookup: minio.BucketLookupPath,
	})
	if err != nil {
		return nil, err
	}

	ctx := context.Background()
	exists, err := client.BucketExists(ctx, bucket)
	if err != nil {
		return nil, err
	}
	if !exists {
		if err := client.MakeBucket(ctx, bucket, minio.MakeBucketOptions{}); err != nil {
			return nil, err
		}
	}

	// Build a second client aimed at the public URL for presigning.
	// Strip scheme — minio-go takes host:port only.
	publicEndpoint := strings.TrimPrefix(strings.TrimPrefix(publicURL, "https://"), "http://")
	publicSSL := strings.HasPrefix(publicURL, "https://")
	presignClient, err := minio.New(publicEndpoint, &minio.Options{
		Creds:        credentials.NewStaticV4(accessKey, secretKey, ""),
		Secure:       publicSSL,
		Region:       "us-east-1",
		BucketLookup: minio.BucketLookupPath,
	})
	if err != nil {
		return nil, fmt.Errorf("presign client: %w", err)
	}

	return &MinioClient{
		client:        client,
		presignClient: presignClient,
		bucket:        bucket,
	}, nil
}

// Upload stores a file in MinIO under the given key.
func (m *MinioClient) Upload(ctx context.Context, key string, reader io.Reader, size int64, contentType string) error {
	_, err := m.client.PutObject(ctx, m.bucket, key, reader, size, minio.PutObjectOptions{
		ContentType: contentType,
	})
	return err
}

// PresignedURL generates a time-limited URL for accessing a private object.
// It uses the public-endpoint client so the HMAC signature matches the URL
// the browser will actually request.
func (m *MinioClient) PresignedURL(ctx context.Context, key string, expiry time.Duration) (string, error) {
	u, err := m.presignClient.PresignedGetObject(ctx, m.bucket, key, expiry, nil)
	if err != nil {
		return "", err
	}
	return u.String(), nil
}

// Stream returns the raw object reader and its size. Caller must close the reader.
func (m *MinioClient) Stream(ctx context.Context, key string) (io.ReadCloser, int64, error) {
	obj, err := m.client.GetObject(ctx, m.bucket, key, minio.GetObjectOptions{})
	if err != nil {
		return nil, 0, err
	}
	info, err := obj.Stat()
	if err != nil {
		obj.Close()
		return nil, 0, err
	}
	return obj, info.Size, nil
}

// Delete removes an object from MinIO.
func (m *MinioClient) Delete(ctx context.Context, key string) error {
	return m.client.RemoveObject(ctx, m.bucket, key, minio.RemoveObjectOptions{})
}
