apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: readr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: readr
spec:
  selector:
    app: redis
  ports:
    - port: 6379
