apiVersion: v1
kind: Secret
metadata:
  name: readr-secrets
  namespace: readr
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.env.JWT_SECRET | quote }}
  JWT_REFRESH_SECRET: {{ .Values.api.env.JWT_REFRESH_SECRET | quote }}
  MONGO_URI: "mongodb://mongodb-svc:27017/readr"
  REDIS_ADDR: "redis-svc:6379"
  MINIO_ENDPOINT: "minio-svc:9000"
  MINIO_ACCESS_KEY: {{ .Values.minio.rootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.rootPassword | quote }}
  MINIO_BUCKET: {{ .Values.minio.bucket | quote }}
